In [ ]:
import os
!git config --global http.proxy socks5 127.0.0.1:10809
!git config --global https.proxy socks5 127.0.0.1:10809

!git config --global http.proxy 127.0.0.1:10809
!git config --global https.proxy 127.0.0.1:10809
print(f"{os.getcwd()}")
!git clone https://huggingface.co/amphion/MaskGCT

In [8]:
import math

x = 100

# 计算自然对数
log_e = math.log(x)  # 默认以e为底

# 计算以10为底的对数
log_10 = math.log10(x)

print(f"自然对数 log_e({x}) = {log_e}")
print(f"常用对数 log_10({x}) = {log_10}")

自然对数 log_e(100) = 4.605170185988092
常用对数 log_10(100) = 2.0


In [1]:
import torch

# 定义向量
v = torch.tensor([1.0, 2.0])

# 定义矩阵
A = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# 矩阵与向量相乘
result = torch.matmul(A, v)
print(result)

# 计算矩阵的逆
A_inv = torch.inverse(A)
print(A_inv)

# 验证矩阵乘以它的逆是否得到单位矩阵
identity = torch.matmul(A, A_inv)
print(identity)

tensor([ 5., 11.])
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])
tensor([[1., 0.],
        [0., 1.]])
